package com.traceon.batur.utils

object AppConstant {
    const val DB_LAHAN = "lahans"
    const val DB_PETANI = "petanis"
    const val DB_KOMODITAS = "komoditases"
    const val DB_BASELINE = "baselines"
    const val DB_REFERRAL = "referrals"
    const val DB_SATUAN = "satuans"

    const val NAME = "name"
    const val EMAIL = "email"
    const val PHONE = "phone"
    const val ALAMAT = "alamat"
    const val ID = "id"
    const val TOKEN = "token"
    const val TABLE_NAME = "table_name"
    const val KODE_PERUSAHAAN = "kode_perusahaan"
    const val ID_AREA = "id_area"
    const val BASELINE = "baseline"
    const val DATABASE = "database"
    const val FOTO = "foto"
    const val ID_DESA = "id_desa"
    const val NAMA_DESA = "nama_desa"
    const val SELECTED_DESA = "selected_desa"
    const val SUCCESS = "success"
    const val LOGIN = "login"
    const val SCAN_QR = 1234
    const val DATA = "data"
    const val AREA = "area"
    const val MU = "mu"
    const val PROGRAM = "program"
    const val KOMODITAS = "komoditas"
    const val ID_PROGRAM = "id_program"
    const val ID_KOMODITAS = "id_komoditas"
}